const expressionInput = document.querySelector('#expression');
const generateButton = document.querySelector('#generateButton');
const output = document.querySelector('#tacOutput');
const notification = document.querySelector('#notification');
const status = document.querySelector('#outputStatus');
const apiBase = window.TAC_API_URL || (window.location.port === '3000' ? '' : 'http://localhost:3000');
let lastTac = '';

function showNotification(message) {
  notification.textContent = message;
  notification.classList.toggle('show', Boolean(message));
}

function calculateStats(expression, tac) {
  const tokens = expression.match(/[A-Za-z_][A-Za-z0-9_]*|\d+(?:\.\d+)?|[()+\-*/%=]/g) || [];
  const instructions = tac ? tac.split('\n').filter(Boolean) : [];
  document.querySelector('#tokenStat').textContent = tokens.length;
  document.querySelector('#operatorStat').textContent = tokens.filter(token => /^[+\-*/%]$/.test(token)).length;
  document.querySelector('#temporaryStat').textContent = (tac.match(/\bt\d+\b/g) || []).filter((value, index, list) => list.indexOf(value) === index).length;
  document.querySelector('#instructionStat').textContent = instructions.length;
  document.querySelector('#instructionCount').textContent = `${instructions.length} instruction${instructions.length === 1 ? '' : 's'}`;
}

function highlight(line) {
  return line.replace(/\b(t\d+)\b/g, '<span class="temp">$1</span>').replace(/([+\-*/%])/g, '<span class="operator">$1</span>').replace(/=/g, '<span class="assign">=</span>');
}

function renderTac(tac) {
  const lines = tac.split('\n').filter(Boolean);
  output.classList.remove('empty');
  output.innerHTML = lines.map((line, index) => `<div class="tac-line" style="animation-delay:${index * 90}ms">${highlight(line)}</div>`).join('');
  status.textContent = 'Generated by the C compiler engine';
  lastTac = tac;
  calculateStats(expressionInput.value, tac);
}

async function generateTac() {
  const expression = expressionInput.value.trim();
  if (!expression) return showNotification('Invalid Expression: please enter an assignment to generate TAC.');
  showNotification('');
  generateButton.classList.add('loading');
  generateButton.disabled = true;
  status.textContent = 'Parsing expression...';
  try {
    const response = await fetch(`${apiBase}/api/generate`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ expression }) });
    const contentType = response.headers.get('content-type') || '';
    const data = contentType.includes('application/json') ? await response.json() : { error: 'Backend server se JSON response nahi mila. Pehle npm start run karein.' };
    if (!response.ok) throw new Error(data.error || 'Invalid Expression');
    renderTac(data.tac);
    showNotification('TAC generated successfully.');
  } catch (error) {
    output.classList.add('empty');
    output.innerHTML = '<span class="output-placeholder">// No output: fix the expression and try again</span>';
    status.textContent = 'Generation failed';
    showNotification(`Invalid Expression: ${error.message.replace(/^Invalid Expression\s*/i, '')}`);
    calculateStats(expressionInput.value, '');
  } finally {
    generateButton.classList.remove('loading');
    generateButton.disabled = false;
  }
}

generateButton.addEventListener('click', generateTac);
expressionInput.addEventListener('keydown', event => { if ((event.ctrlKey || event.metaKey) && event.key === 'Enter') generateTac(); });
document.querySelector('#clearInput').addEventListener('click', () => { expressionInput.value = ''; expressionInput.focus(); });
document.querySelector('#loadExample').addEventListener('click', () => { expressionInput.value = 'result = (a + b) * c'; expressionInput.focus(); });
document.querySelector('#clearOutput').addEventListener('click', () => { lastTac = ''; output.className = 'code-output empty'; output.innerHTML = '<span class="output-placeholder">// Your generated instructions will appear here</span>'; status.textContent = 'Waiting for an expression'; calculateStats(expressionInput.value, ''); showNotification(''); });
document.querySelector('#copyCode').addEventListener('click', async () => { if (!lastTac) return; await navigator.clipboard.writeText(lastTac); showNotification('TAC copied to your clipboard.'); });
document.querySelector('#downloadCode').addEventListener('click', () => { if (!lastTac) return; const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([lastTac], { type: 'text/plain' })); link.download = 'generated.tac'; link.click(); URL.revokeObjectURL(link.href); });
document.querySelectorAll('.example-card').forEach(card => card.addEventListener('click', () => { expressionInput.value = card.dataset.expression; document.querySelector('#workspace').scrollIntoView({ behavior: 'smooth' }); setTimeout(generateTac, 350); }));